# Generated by Django 6.0.6 on 2026-10-01 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_social_profiles_and_follows'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=1000)),
                ('technologies', models.CharField(max_length=300)),
                ('github_url', models.URLField(blank=True, max_length=300)),
                ('live_url', models.URLField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='projects/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='blog.userprofile')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
